FROM node:16.20.0-alpine3.16

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

COPY package.json ./
COPY package-lock.json ./

RUN npm install --silent

COPY . ./