version: "3.8"

services:
  backend_fastapi:
    container_name: backend_fastapi_dev
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./backend/app/db/.env
  frontend:
    container_name: frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm run dev
    volumes:
      - "./frontend:/app"
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    container_name: postgresql_dev
    image: postgres:15.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./backend/app/db/.env
    environment:
      - POSTGRES_USER=customer_process_system_dev
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_DB=customer_process_system_db
volumes:
  postgres_data:
