version: "3.7"

services:
  backend_fastapi:
    container_name: backend_fastapi_dev
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend/:/usr/src/app/
    ports:
      - 8000:8000
  frontend:
    container_name: frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    command: npm start
    volumes: 
      - '.:/app'
      - '/app/node_modules'
    ports: 
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  db:
    container_name: postgresql_bue_dev
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=customer_process_system
      - POSTGRES_PASSWORD=customer_process_system
      - POSTGRES_DB=customer_process_system_dev
volumes:
  postgres_data: